// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa9_hX2tftUCvBTidCGvLKXuiH5uYBluU',
    appId: '1:542163507398:web:39f8664ada3315adf69fc7',
    messagingSenderId: '542163507398',
    projectId: 'mskool-6b32d',
    authDomain: 'mskool-6b32d.firebaseapp.com',
    storageBucket: 'mskool-6b32d.appspot.com',
    measurementId: 'G-NQPJH2HZ2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArCbgvnuDOyba452Gt8Irc-9RTb3mF_7M',
    appId: '1:542163507398:android:4c5d63a6f1d08c84f69fc7',
    messagingSenderId: '542163507398',
    projectId: 'mskool-6b32d',
    storageBucket: 'mskool-6b32d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUN8yDXrIGXde2vBwEzXNCH4YITy1Z9cY',
    appId: '1:542163507398:ios:1f4bd4dd906b1d2ff69fc7',
    messagingSenderId: '542163507398',
    projectId: 'mskool-6b32d',
    storageBucket: 'mskool-6b32d.appspot.com',
    iosClientId: '542163507398-a3pit8l3r1iiduoph5v3a6is2qd55uek.apps.googleusercontent.com',
    iosBundleId: 'com.example.mSkoolFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUN8yDXrIGXde2vBwEzXNCH4YITy1Z9cY',
    appId: '1:542163507398:ios:1f4bd4dd906b1d2ff69fc7',
    messagingSenderId: '542163507398',
    projectId: 'mskool-6b32d',
    storageBucket: 'mskool-6b32d.appspot.com',
    iosClientId: '542163507398-a3pit8l3r1iiduoph5v3a6is2qd55uek.apps.googleusercontent.com',
    iosBundleId: 'com.example.mSkoolFlutter',
  );
}
